---
title: 'Advanced Hypotheses'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/NjEyOTIyMzMyOTk2/a/NjE1MDk5NTI5MjE4/details
---

By this point you should feel good about the kinds of simple hypotheses you can make about your project data. Our goal here is to help you advance your understanding of appropriate hypotheses and give you some skills to test more advanced ideas.

Your initial hypotheses in [Level 2](../level-2/) may have ended up addressing fundamental features that you already really expected to be true. It's a solid way to start on any observational study - focus in on the things you expect to be true and pay attention to anything that doesn't fit your model of how the world works. 

Another important step is to use your literature review to highlight aspects of the system that are least well understood. Some of these may have surfaced already for you in reading these papers.

## Exercise

You should begin by writing two paragraphs:

1. A brief description of the hypotheses your group tested and any features that didn't fit these models of how the world should work. This could include any individual data points that didn't fit with a broader trend, a whole stations where there was clearly something else going on, or indeed any hypotheses that the data couldn't confirm.

1. A brief description of the features of your system that seemed less well understood based on your understanding of the literature review you undertook. This could be things that may not be testable with the data we have to hand.

Reflect on these two paragraphs (especially on the first one). They will help guide you towards a creating new research question and associated hypothesis. Think about:

* What processes or other factors might explain the anomalies in your data?
* Do we have data that might allow us to determine the impact of these factors?
* What additional data might you need to explain these trends?

Once you have a new research question and hypothesis we should review this and make a plan. That plan will probably look like one of two paths:

1. Test this new hypothesis bringing in new data streams either from the cruise or from other sources

2. Design a research experiment that could potentially answer your proposed question in the region