---
title: 'Collaboration Memo'
author: Ben Harden
date: '2021-05-05'
level: 3
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/NjEyOTIyMzMyOTk2/a/NjEyOTIyMzMzMDUw/details
---

If you've chosen to complete this level, you should do so in the final week of class. By this time you will have developed a teamwork contract, reviewed it, attended the WHOI Ethic seminar and seem how your class project team has functioned in reality.

In this level we are going to reflect on our in-class collaboration and make some plans for future teamwork in science.

## Teamwork reflection

Start by using the team contract that you developed as a starting point to analyze how you team functioned. You should write a single page reflection that seeks to answer the following:

* In general, what did your team do well and what could have been improved?
* What contribution did you make and did it feel equitable?
* Which particular parts of the contract were useful as a tool to ensure that teamwork progressed as you might hope?
* Which parts were too general/vague to be helpful and how would you change some of them to be more useful?

You should submit this to the assignment below. Once I've had a chance to review it, we can chat about the process.

## Ten Questions

Finally, as a tool for you to use going forward, I'd like you to compose ten questions that you would like to ask yourself the next time you start working as part of a team.

Think about questions that will help you:

* Understand what you can (and want) to bring to the team
* Examine what you might expect form others
* Craft a open, supportive environment
* Generally set both you and the wider team up for success

Submit these questions on the same document as above and we can chat about them.