---
title: 'Community Reflection'
author: Ben Harden
date: '2021-05-05'
level: 2
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/NDg3ODE3MzU4NzEw/a/NTM0MTgzMjQ0OTYy/details
---

I'd like you to focus in on one of the guest speakers that we have heard from and reflect a little deeper on what they had to say and how it connects with you. Choose one of the topics you heard about that particularly resonated with you. That can be for any number of reasons. Maybe you thought the science was interesting or connected to your research interests. Maybe the research topic impacts you or your community directly or indirectly. Perhaps you felt a particular connection to the speaker and how they interacted with your cohort. Or maybe you saw similarities or contrasts with their pathway into science and yours. 

Regardless of the specific reason, you should write a single page reflection (12pt double-spaced) that seeks to explore some (but not necessarily all) of the following:

* What was new or surprising to you?
* What connections did you see between your research interests and the topic presented?
* How does the topic relate to broader questions of how scientists can best serve society?
* How did this help you see yourself and your role as a scientist?
* What did you learn about careers in science more generally?

Submit this reflection to the assignment below