---
title: "Poster Text"
author: Ben Harden
date: '2022-05-05'
level: 2
slug: []
categories: []
tags: []
draft: no
quiz: https://classroom.google.com/c/NDg3ODE3MzU4NzEw/a/NTM1MjIwNDQ5NzEw/details
---

Now that we've seen some options for sections and text that can be used in your poster, you and your team should make some decisions about what you are going to present and in what format.

From your data report, you will have a selection of figures and results. You should look through this together and pick the three (or so) most relevant or interesting results that you want to emphasize in your poster. These results will form the major thrust of the poster so we need to make sure that the figures and text we use all work to support communicating these outcomes. 

Once you've decided on your main results, you should begin thinking about the text and figures that you are going to use. Some of this can be lifted right from your data report, but you will need to cover the information that traditionally goes in the four section so of a research paper:

* Introduction: Basic background information and motivation
* Methods: Briefly how we collected the data
* Results: What we found and what it means
* Discussion: Any conclusions and/or possible further work

Your goal at this level is to produce a team document that is a first draft of the text and figures that are going to go into your poster. Think of it as a polished version of your data report with an eye to the information and structure needed in the research poster.

One final requirement - you really don't have much space for words on a poster so you should limit yourself to 500 words maximum. You will probably find you will even need to scale it down from there as you put the words into your final poster.
