---
title: "What is a Data Report?"
author: Ben Harden
date: '2021-05-05'
level: 1
slug: []
categories: []
tags: []
draft: no
---

For research teams to work on shared research questions successfully, they must find a way to effectively share their ongoing analysis with each other. This often takes the form of data reports or update presentations. Every research team I have worked with did them regularly. They often take the form of brief internal presentations that should provoke discussion and open up analysis for wider review. They are also key for sharing questions/roadblocks with your teams so that you might get input and assistance. They also serve as the basis from which group decisions about research direction and publication possibilities can be made.

For our purposes, I want you to use the data report tool to help organize your results, share them internally with your team (and with me), and work together to test your hypotheses and further analyze your results.

We'll have time to chat a little about this in class and then in Level 2 we will talk about the particulars of what you document should look like.
